import maya

maya.stringTable['y_RigidBody.kAlreadyRigidBody'] = u'{0} contains a bullet rigid shape, will remove before adding to rigid set.'
maya.stringTable['y_RigidBody.kStaticBody'] = u'Static Body'
maya.stringTable['y_RigidBody.kRestitution'] = u'Restitution'
maya.stringTable['y_RigidBody.kInputSetAnnot'] = u'Create a rigid set node to remember the original geometry used to create this set.'
maya.stringTable['y_RigidBody.kInputSet'] = u'Create Input Set'
maya.stringTable['y_RigidBody.kSphere'] = u'Sphere'
maya.stringTable['y_RigidBody.kAxisType'] = u'Axis'
maya.stringTable['y_RigidBody.kDynRigidBody'] = u'Dynamic Rigid Body'
maya.stringTable['y_RigidBody.kHACD'] = u'Auto Compound'
maya.stringTable['y_RigidBody.kCapsule'] = u'Capsule'
maya.stringTable['y_RigidBody.kInitVel'] = u'Initial Velocity'
maya.stringTable['y_RigidBody.kMesh'] = u'Mesh (static only)'
maya.stringTable['y_RigidBody.kGetOptVarValues'] = u'Get optionVar values'
maya.stringTable['y_RigidBody.kLongNameAmbiguity'] = u'more than one object matches %s'
maya.stringTable['y_RigidBody.kAngDamp'] = u'Angular Damping'
maya.stringTable['y_RigidBody.kErrorDeleteNoRigidSetSelected'] = u'Please select the rigid sets to delete.'
maya.stringTable['y_RigidBody.kErrorRigidBodyNotCreated'] = u'Failed to create rigid body object; please check that the bullet plugin is loaded.'
maya.stringTable['y_RigidBody.kRadius'] = u'Radius'
maya.stringTable['y_RigidBody.kColliderShapeOffset'] = u'Collider Shape Offset'
maya.stringTable['y_RigidBody.kHideInputGeometryAnnot'] = u"Change the input geometry's visibility to false after creating the rigid set."
maya.stringTable['y_RigidBody.kPlane'] = u'Plane'
maya.stringTable['y_RigidBody.kErrorClearNoRigidSetSelected'] = u'Please select the rigid sets to empty.'
maya.stringTable['y_RigidBody.kAutoHide'] = u'Hide Rigid Body Shape'
maya.stringTable['y_RigidBody.kOutputMeshAnnot'] = u'Create a new geometry node combining all input geometries.'
maya.stringTable['y_RigidBody.kLinearDamp'] = u'Linear Damping'
maya.stringTable['y_RigidBody.kErrorNoRigidSetSelected'] = u'Please include the rigid sets in the current selection'
maya.stringTable['y_RigidBody.kColliderType'] = u'Collider Shape Type'
maya.stringTable['y_RigidBody.kCylinder'] = u'Cylinder'
maya.stringTable['y_RigidBody.kAmbiguousAddToSet'] = u'More than one rigid set selected.'
maya.stringTable['y_RigidBody.kCenterOfMass'] = u'Center of Mass'
maya.stringTable['y_RigidBody.kNone'] = u'None'
maya.stringTable['y_RigidBody.kSelectedObjects'] = u'Use Selected Objects'
maya.stringTable['y_RigidBody.kTorqueImpulse'] = u'Torque Impulse'
maya.stringTable['y_RigidBody.kYAxis'] = u'Y'
maya.stringTable['y_RigidBody.kMass'] = u'Mass'
maya.stringTable['y_RigidBody.kErrorNoRigidSetMemberSelected'] = u'Please select at least one transform object.'
maya.stringTable['y_RigidBody.kLength'] = u'Length'
maya.stringTable['y_RigidBody.kKinematicRigidBody'] = u'Kinematic Rigid Body'
maya.stringTable['y_RigidBody.kXAxis'] = u'X'
maya.stringTable['y_RigidBody.kHideInputGeometry'] = u'Hide Input Geometry'
maya.stringTable['y_RigidBody.kZAxis'] = u'Z'
maya.stringTable['y_RigidBody.kInitAngVel'] = u'Initial Angular Velocity'
maya.stringTable['y_RigidBody.kSetName'] = u'Name'
maya.stringTable['y_RigidBody.kExtents'] = u'Extents'
maya.stringTable['y_RigidBody.kExecuteCmd'] = u'Execute command'
maya.stringTable['y_RigidBody.kBodyType'] = u'Body Type'
maya.stringTable['y_RigidBody.kCompound'] = u'Compound'
maya.stringTable['y_RigidBody.kOutputMesh'] = u'Create Output Mesh'
maya.stringTable['y_RigidBody.kHull'] = u'Hull'
maya.stringTable['y_RigidBody.kSelectedObjectsAnnot'] = u'Use the selected geometry as the initial members of the rigid set.'
maya.stringTable['y_RigidBody.kAutoFit'] = u'Auto Fit'
maya.stringTable['y_RigidBody.kFriction'] = u'Friction'
maya.stringTable['y_RigidBody.kImpulse'] = u'Impulse'
maya.stringTable['y_RigidBody.kCreateRigidSet'] = u'Create Rigid Body Set'
maya.stringTable['y_RigidBody.kInitSleep'] = u'Initially Sleeping'
maya.stringTable['y_RigidBody.kAlreadyBulletObject2'] = u'The selected object ({0}) is already a bullet object'
maya.stringTable['y_RigidBody.kCreateRigidBody'] = u'Create Rigid Body'
maya.stringTable['y_RigidBody.kBox'] = u'Box'
maya.stringTable['y_RigidBody.kNoRigidSetToAddSelected'] = u'There is no rigid set selected.'
maya.stringTable['y_RigidBody.kNeverSleeps'] = u'Never Sleeps'
maya.stringTable['y_RigidBody.kColliderShapeMargin'] = u'Collider Shape Margin'

# ===========================================================================
# Copyright 2016 Autodesk, Inc. All rights reserved.
#
# Use of this software is subject to the terms of the Autodesk license
# agreement provided at the time of installation or download, or which
# otherwise accompanies this software in either electronic or hard copy form.
# ===========================================================================
