import maya

maya.stringTable['y_shelfEditorWindow.kHelp'] = u'Help'
maya.stringTable['y_shelfEditorWindow.kShelfCommand'] = u'Command'
maya.stringTable['y_shelfEditorWindow.kItemUserColor'] = u'Custom Background Color'
maya.stringTable['y_shelfEditorWindow.kItemName'] = u'Rename:'
maya.stringTable['y_shelfEditorWindow.kMoveDown'] = u'Move Down'
maya.stringTable['y_shelfEditorWindow.kButtonBackgroundColor'] = u'Button Background:'
maya.stringTable['y_shelfEditorWindow.kIconOnly'] = u'Icon Only'
maya.stringTable['y_shelfEditorWindow.kIconName'] = u'Icon Name:'
maya.stringTable['y_shelfEditorWindow.kTextColor'] = u'Icon Label Color:'
maya.stringTable['y_shelfEditorWindow.kNewItem'] = u'New Item'
maya.stringTable['y_shelfEditorWindow.kMenuItemCommand'] = u'Menu Item Command'
maya.stringTable['y_shelfEditorWindow.kPickIconCaption'] = u'Open'
maya.stringTable['y_shelfEditorWindow.kDeleteShelf'] = u'Delete Shelf'
maya.stringTable['y_shelfEditorWindow.kMenuItems'] = u'Menu Items'
maya.stringTable['y_shelfEditorWindow.kLanguage'] = u'Language:'
maya.stringTable['y_shelfEditorWindow.kTextBelow'] = u'Icon/Text Below'
maya.stringTable['y_shelfEditorWindow.kMoveUp'] = u'Move Up'
maya.stringTable['y_shelfEditorWindow.kShelfEditor'] = u'Shelf Editor'
maya.stringTable['y_shelfEditorWindow.kOptions'] = u'Options'
maya.stringTable['y_shelfEditorWindow.kShelves'] = u'Shelves'
maya.stringTable['y_shelfEditorWindow.kBackgroundTransparency'] = u'Background Transparency:'
maya.stringTable['y_shelfEditorWindow.kRepeatable'] = u'Repeatable'
maya.stringTable['y_shelfEditorWindow.kSaveonRequest'] = u'Save Only on Request'
maya.stringTable['y_shelfEditorWindow.kDeleteItem'] = u'Delete Item'
maya.stringTable['y_shelfEditorWindow.kShelfLeft'] = u'Left'
maya.stringTable['y_shelfEditorWindow.kItemTooltip'] = u'Tooltip:'
maya.stringTable['y_shelfEditorWindow.kShelfName'] = u'Rename:'
maya.stringTable['y_shelfEditorWindow.kShelfAlignment'] = u'Alignment:'
maya.stringTable['y_shelfEditorWindow.kBrowseImage'] = u'Browse user defined icons'
maya.stringTable['y_shelfEditorWindow.kClose'] = u'Close'
maya.stringTable['y_shelfEditorWindow.kNewMenuItem'] = u'New Menu Item'
maya.stringTable['y_shelfEditorWindow.kBackgroundColor'] = u'Label Background:'
maya.stringTable['y_shelfEditorWindow.kMenuItemName'] = u'Rename:'
maya.stringTable['y_shelfEditorWindow.kNewShelf'] = u'New Shelf'
maya.stringTable['y_shelfEditorWindow.kIcon'] = u'Icon Preview:'
maya.stringTable['y_shelfEditorWindow.kSaveAllShelves'] = u'Save All Shelves'
maya.stringTable['y_shelfEditorWindow.kSaveAutomatically'] = u'Save Automatically'
maya.stringTable['y_shelfEditorWindow.kTextBeside'] = u'Icon/Text Beside'
maya.stringTable['y_shelfEditorWindow.kItemLabel'] = u'Icon Label:'
maya.stringTable['y_shelfEditorWindow.kShelfContent'] = u'Shelf Contents'
maya.stringTable['y_shelfEditorWindow.kDeleteMenuItem'] = u'Delete Menu Item'
maya.stringTable['y_shelfEditorWindow.kShelfDblCommand'] = u'Double Click Command'
maya.stringTable['y_shelfEditorWindow.kTextOnly'] = u'Text Only'
maya.stringTable['y_shelfEditorWindow.kShelfMenuItems'] = u'Popup Menu Items'
maya.stringTable['y_shelfEditorWindow.kShelfRight'] = u'Right'
maya.stringTable['y_shelfEditorWindow.kLanguage2'] = u'Language:'
maya.stringTable['y_shelfEditorWindow.kMayaIcons'] = u'Browse Maya icons'
maya.stringTable['y_shelfEditorWindow.kShelfList'] = u'Shelves'
maya.stringTable['y_shelfEditorWindow.kHelponShelves'] = u'Help on Shelves'

# ===========================================================================
# Copyright 2016 Autodesk, Inc. All rights reserved.
#
# Use of this software is subject to the terms of the Autodesk license
# agreement provided at the time of installation or download, or which
# otherwise accompanies this software in either electronic or hard copy form.
# ===========================================================================
